### ISSUE TITLE
Moving all IDs to only one file

### ISSUE THREAD

**Issue by peonso** [Inconcessus/OTMapGen#3]
It would be interesting to have only constants in both OTMapGen.js and border.js and move all ids to a single files, so people could easily change for using 7.6 ids, or [OpenTibia Sprite Pack](https://github.com/peonso/opentibia_sprite_pack), or a complete different set of 10.98 tiles.

**Comment by Inconcessus** [comment]
So you mean like having a file e.g. `ids.json` that has all defined constants that are now in the bordering functions:

    {
        "MOUNTAIN_WALL_NORTH": 0000,
        "MOUNTAIN_WALL_SOUTH": 0001,
        ....
    }

**Comment by Inconcessus** [comment]
That was a chore! But done in 523bc7cb1d86064ad56bc77ab9bf809b941c816d.
